# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98e0acf7056ce269c9cdff3852ebc2b718628d817737efc0c6725b4abb276163c377a4b380f053d7328310bd35c9248f09cb5981f23e4978c7ef116de0857e0b

test:
  secret_key_base: b40449407f5482f299c966f21d4eeb5868d35e3ea9c02780e6bdf657195022281823df2027fa7c6f95c60b6ea0cc410ba3c6092023583cfa81acbc1043279404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
